=== zaidfa/language-pack-repository/schemas/layout.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/schemas/layout.schema.json",
  "title": "Keyboard Layout",
  "type": "object",
  "required": ["schemaVersion", "tag", "layers"],
  "properties": {
    "schemaVersion": { "type": "integer", "enum": [1] },
    "tag": { "type": "string" },
    "script": { "type": "string" },
    "direction": { "type": "string", "enum": ["ltr", "rtl"] },
    "cased": { "type": "boolean" },
    "layoutType": { "type": "string" },
    "inputMethod": { "type": "string" },
    "note": { "type": "string" },
    "layers": {
      "type": "object",
      "required": ["default"],
      "additionalProperties": { "$ref": "#/definitions/rows" }
    }
  },
  "definitions": {
    "rows": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "array",
        "minItems": 1,
        "items": { "$ref": "#/definitions/key" }
      }
    },
    "key": {
      "oneOf": [
        { "type": "string", "minLength": 1 },
        {
          "type": "object",
          "properties": {
            "o": { "type": "string" },
            "l": { "type": "string" },
            "hold": { "type": "array", "items": { "type": "string", "minLength": 1 } },
            "code": { "type": "string", "enum": ["SHIFT", "DELETE", "ENTER", "SPACE", "SYMBOLS", "SYMBOLS2", "ABC", "EMOJI", "LANG", "MODE"] },
            "w": { "type": "number", "minimum": 0.1 }
          },
          "anyOf": [ { "required": ["o"] }, { "required": ["code"] } ]
        }
      ]
    }
  }
}

=== zaidfa/language-pack-repository/packs/sl/layout.json
{
  "cased": true,
  "direction": "ltr",
  "inputMethod": "direct",
  "layers": {
    "default": [
      [
        "q",
        "w",
        "e",
        "r",
        "t",
        {
          "hold": [
            "ž"
          ],
          "o": "z"
        },
        "u",
        "i",
        "o",
        "p"
      ],
      [
        "a",
        {
          "hold": [
            "š"
          ],
          "o": "s"
        },
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l"
      ],
      [
        {
          "code": "SHIFT",
          "l": "⇧",
          "w": 1.5
        },
        "y",
        "x",
        {
          "hold": [
            "č"
          ],
          "o": "c"
        },
        "v",
        "b",
        "n",
        "m",
        {
          "code": "DELETE",
          "l": "⌫",
          "w": 1.5
        }
      ],
      [
        {
          "code": "SYMBOLS",
          "l": "?123",
          "w": 1.5
        },
        {
          "code": "LANG",
          "l": "🌐"
        },
        {
          "code": "EMOJI",
          "l": "☺"
        },
        ",",
        {
          "code": "SPACE",
          "l": "",
          "o": " ",
          "w": 4
        },
        ".",
        {
          "code": "ENTER",
          "l": "⏎",
          "w": 1.5
        }
      ]
    ]
  },
  "layoutType": "direct",
  "schemaVersion": 1,
  "script": "Latn",
  "tag": "sl"
}

=== zaidfa/language-pack-repository/packs/hu/layout.json
{
  "cased": true,
  "direction": "ltr",
  "inputMethod": "direct",
  "layers": {
    "default": [
      [
        "q",
        "w",
        {
          "hold": [
            "é"
          ],
          "o": "e"
        },
        "r",
        "t",
        "z",
        {
          "hold": [
            "ú",
            "ü",
            "ű"
          ],
          "o": "u"
        },
        {
          "hold": [
            "í"
          ],
          "o": "i"
        },
        {
          "hold": [
            "ó",
            "ö",
            "ő"
          ],
          "o": "o"
        },
        "p"
      ],
      [
        {
          "hold": [
            "á"
          ],
          "o": "a"
        },
        "s",
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l"
      ],
      [
        {
          "code": "SHIFT",
          "l": "⇧",
          "w": 1.5
        },
        "y",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        {
          "code": "DELETE",
          "l": "⌫",
          "w": 1.5
        }
      ],
      [
        {
          "code": "SYMBOLS",
          "l": "?123",
          "w": 1.5
        },
        {
          "code": "LANG",
          "l": "🌐"
        },
        {
          "code": "EMOJI",
          "l": "☺"
        },
        ",",
        {
          "code": "SPACE",
          "l": "",
          "o": " ",
          "w": 4
        },
        ".",
        {
          "code": "ENTER",
          "l": "⏎",
          "w": 1.5
        }
      ]
    ]
  },
  "layoutType": "direct",
  "schemaVersion": 1,
  "script": "Latn",
  "tag": "hu"
}

=== zaidfa/language-pack-repository/packs/uk/layout.json
{
  "cased": true,
  "direction": "ltr",
  "inputMethod": "direct",
  "layers": {
    "default": [
      [
        "й",
        "ц",
        "у",
        "к",
        "е",
        "н",
        {
          "hold": [
            "ґ"
          ],
          "o": "г"
        },
        "ш",
        "щ",
        "з",
        "х"
      ],
      [
        "ф",
        {
          "hold": [
            "ї"
          ],
          "o": "і"
        },
        "в",
        "а",
        "п",
        "р",
        "о",
        "л",
        "д",
        "ж",
        "є"
      ],
      [
        {
          "code": "SHIFT",
          "l": "⇧",
          "w": 1.5
        },
        "я",
        "ч",
        "с",
        "м",
        "и",
        "т",
        "ь",
        "б",
        "ю",
        {
          "code": "DELETE",
          "l": "⌫",
          "w": 1.5
        }
      ],
      [
        {
          "code": "SYMBOLS",
          "l": "?123",
          "w": 1.5
        },
        {
          "code": "LANG",
          "l": "🌐"
        },
        {
          "code": "EMOJI",
          "l": "☺"
        },
        ",",
        {
          "code": "SPACE",
          "l": "",
          "o": " ",
          "w": 4
        },
        ".",
        {
          "code": "ENTER",
          "l": "⏎",
          "w": 1.5
        }
      ]
    ]
  },
  "layoutType": "direct",
  "schemaVersion": 1,
  "script": "Cyrl",
  "tag": "uk"
}

=== zaidfa/language-pack-repository/packs/as/layout.json
{
  "cased": false,
  "direction": "ltr",
  "inputMethod": "direct",
  "layers": {
    "default": [
      [
        "ঔ",
        "ঐ",
        "আ",
        "ঈ",
        "ঊ",
        "ব",
        "হ",
        "গ",
        "দ",
        "জ",
        "ড"
      ],
      [
        "ও",
        "এ",
        "অ",
        "ি",
        "ু",
        "প",
        {
          "hold": [
            "ৱ"
          ],
          "o": "ৰ"
        },
        {
          "hold": [
            "ক্ষ"
          ],
          "o": "ক"
        },
        "ত",
        "চ",
        "ট"
      ],
      [
        "ং",
        "ম",
        "ন",
        "ল",
        "স",
        "শ",
        "ষ",
        {
          "code": "DELETE",
          "l": "⌫",
          "w": 1.5
        }
      ],
      [
        {
          "code": "SYMBOLS",
          "l": "?123",
          "w": 1.5
        },
        {
          "code": "LANG",
          "l": "🌐"
        },
        {
          "code": "EMOJI",
          "l": "☺"
        },
        ",",
        {
          "code": "SPACE",
          "l": "",
          "o": " ",
          "w": 4
        },
        ".",
        {
          "code": "ENTER",
          "l": "⏎",
          "w": 1.5
        }
      ]
    ]
  },
  "layoutType": "complex",
  "note": "Assamese ৰ/ৱ included; direct Unicode entry.",
  "schemaVersion": 1,
  "script": "Beng",
  "tag": "as"
}

=== zaidfa/language-pack-repository/packs/mk/layout.json
{
  "cased": true,
  "direction": "ltr",
  "inputMethod": "direct",
  "layers": {
    "default": [
      [
        "љ",
        "њ",
        "е",
        "р",
        "т",
        "ѕ",
        "у",
        "и",
        "о",
        "п",
        "ш"
      ],
      [
        "а",
        "с",
        "д",
        "ф",
        "г",
        "х",
        "ј",
        "к",
        "л",
        "ч",
        "ќ"
      ],
      [
        {
          "code": "SHIFT",
          "l": "⇧",
          "w": 1.5
        },
        "џ",
        "ц",
        "в",
        "б",
        "н",
        "м",
        "ѓ",
        "ж",
        {
          "code": "DELETE",
          "l": "⌫",
          "w": 1.5
        }
      ],
      [
        {
          "code": "SYMBOLS",
          "l": "?123",
          "w": 1.5
        },
        {
          "code": "LANG",
          "l": "🌐"
        },
        {
          "code": "EMOJI",
          "l": "☺"
        },
        ",",
        {
          "code": "SPACE",
          "l": "",
          "o": " ",
          "w": 4
        },
        ".",
        {
          "code": "ENTER",
          "l": "⏎",
          "w": 1.5
        }
      ]
    ]
  },
  "layoutType": "direct",
  "schemaVersion": 1,
  "script": "Cyrl",
  "tag": "mk"
}

=== zaidfa/language-pack-repository/packs/nb/layout.json
{
  "cased": true,
  "direction": "ltr",
  "inputMethod": "direct",
  "layers": {
    "default": [
      [
        "q",
        "w",
        {
          "hold": [
            "é"
          ],
          "o": "e"
        },
        "r",
        "t",
        "y",
        "u",
        "i",
        {
          "hold": [
            "ø"
          ],
          "o": "o"
        },
        "p"
      ],
      [
        {
          "hold": [
            "å",
            "æ"
          ],
          "o": "a"
        },
        "s",
        "d",
        "f",
        "g",
        "h",
        "j",
        "k",
        "l"
      ],
      [
        {
          "code": "SHIFT",
          "l": "⇧",
          "w": 1.5
        },
        "z",
        "x",
        "c",
        "v",
        "b",
        "n",
        "m",
        {
          "code": "DELETE",
          "l": "⌫",
          "w": 1.5
        }
      ],
      [
        {
          "code": "SYMBOLS",
          "l": "?123",
          "w": 1.5
        },
        {
          "code": "LANG",
          "l": "🌐"
        },
        {
          "code": "EMOJI",
          "l": "☺"
        },
        ",",
        {
          "code": "SPACE",
          "l": "",
          "o": " ",
          "w": 4
        },
        ".",
        {
          "code": "ENTER",
          "l": "⏎",
          "w": 1.5
        }
      ]
    ]
  },
  "layoutType": "direct",
  "schemaVersion": 1,
  "script": "Latn",
  "tag": "nb"
}

=== zaidfa/language-pack-repository/packs/tr/layout.json
{
  "cased": true,
  "direction": "ltr",
  "inputMethod": "direct",
  "layers": {
    "default": [
      [
        "q",
        "w",
        "e",
        "r",
        "t",
        "y",
        {
          "hold": [
            "ü"
          ],
          "o": "u"
        },
        {
          "hold": [
            "ı"
          ],
          "o": "i"
        },
        {
          "hold": [
            "ö"
          ],
          "o": "o"
        },
        "p"
      ],
      [
        "a",
        {
          "hold": [
            "ş"
          ],
          "o": "s"
        },
        "d",
        "f",
        {
          "hold": [
            "ğ"
          ],
          "o": "g"
        },
        "h",
        "j",
        "k",
        "l"
      ],
      [
        {
          "code": "SHIFT",
          "l": "⇧",
          "w": 1.5
        },
        "z",
        "x",
        {
          "hold": [
            "ç"
          ],
          "o": "c"
        },
        "v",
        "b",
        "n",
        "m",
        {
          "code": "DELETE",
          "l": "⌫",
          "w": 1.5
        }
      ],
      [
        {
          "code": "SYMBOLS",
          "l": "?123",
          "w": 1.5
        },
        {
          "code": "LANG",
          "l": "🌐"
        },
        {
          "code": "EMOJI",
          "l": "☺"
        },
        ",",
        {
          "code": "SPACE",
          "l": "",
          "o": " ",
          "w": 4
        },
        ".",
        {
          "code": "ENTER",
          "l": "⏎",
          "w": 1.5
        }
      ]
    ]
  },
  "layoutType": "direct",
  "schemaVersion": 1,
  "script": "Latn",
  "tag": "tr"
}

=== zaidfa/language-pack-repository/packs/be/layout.json
{
  "cased": true,
  "direction": "ltr",
  "inputMethod": "direct",
  "layers": {
    "default": [
      [
        "й",
        "ц",
        "у",
        "к",
        "е",
        "н",
        "г",
        "ш",
        "ў",
        "з",
        "х"
      ],
      [
        "ф",
        "ы",
        "в",
        "а",
        "п",
        "р",
        "о",
        "л",
        "д",
        "ж",
        "э"
      ],
      [
        {
          "code": "SHIFT",
          "l": "⇧",
          "w": 1.5
        },
        "я",
        "ч",
        "с",
        "м",
        "і",
        "т",
        {
          "hold": [
            "ъ"
          ],
          "o": "ь"
        },
        "б",
        "ю",
        {
          "code": "DELETE",
          "l": "⌫",
          "w": 1.5
        }
      ],
      [
        {
          "code": "SYMBOLS",
          "l": "?123",
          "w": 1.5
        },
        {
          "code": "LANG",
          "l": "🌐"
        },
        {
          "code": "EMOJI",
          "l": "☺"
        },
        ",",
        {
          "code": "SPACE",
          "l": "",
          "o": " ",
          "w": 4
        },
        ".",
        {
          "code": "ENTER",
          "l": "⏎",
          "w": 1.5
        }
      ]
    ]
  },
  "layoutType": "direct",
  "schemaVersion": 1,
  "script": "Cyrl",
  "tag": "be"
}
